// Generated by CoffeeScript 1.6.3
(function(window, document) {
  var Validate;
  return Validate = (function() {
    var email, form, msg, name, site, v;

    function Validate() {}

    name = document.getElementById('name');

    email = document.getElementById('email');

    site = document.getElementById('site');

    msg = document.getElementById('message');

    form = document.getElementById('contact_form');

    form.addEventListner('submit', function() {});

    Validate.prototype.init = function() {};

    v = new Validate();

    v.init();

    return Validate;

  })();
})(window, document);
